### ISSUE TITLE
fails to build with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [tolysz/rawstring-qm#3]
For Stackage Nightly with ghc-9.10.2:

```
       Building library for rawstring-qm-0.2.3.0...                                                                                 
       [2 of 3] Compiling Data.Text.ToText                                                                                          
       /home/curators/work/unpack-dir/unpacked/rawstring-qm-0.2.3.0-3759ed915f2c663b5415a9085e8a23cd4bf404baed4b52236b19127754c0d445
/src/Data/Text/ToText.hs:36:91: error: [GHC-87543]                                                                                  
           Ambiguous occurrence ‘show’.                                                                                             
           It could refer to                                                                                                        
              either ‘Prelude.show’,                                                                                                
                     imported from ‘Prelude’ at src/Data/Text/ToText.hs:11:1-14                                                     
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),                                         
                  or ‘Data.Text.show’,                                                                                              
                     imported from ‘Data.Text’ at src/Data/Text/ToText.hs:12:1-16.                                                  
          |                                                                                                                         
       36 |     fromText v = maybe (Left $ "parse failed: `" <> v <>"` can not be parsed as" <> pack (show (typeOf (undefined :: a))
) ) Right . readMaybe . unpack $ v                                                                                                  
          |                                                                                           ^^^^
```

**Comment by tolysz** [comment]
fixed in: rawstring-qm-0.2.3.1
